### ISSUE TITLE
.yoo-ni     폴더 생성, 정리 질문 입니다.

### ISSUE THREAD

**Issue by my-zzu** [rebehayan/SCSS-4th-Project#1]
안녕하세요.
2차시 수업후에 폴더 생성, 정리 하는 부분 부터 복습하였습니다.

프로젝트 폴더 안에,
scss폴더, pages폴더, images폴더, style.scss파일를 만들고,

scss폴더 안에,
abstracts, base, components, layouy, page, vendor 폴더들을 만들고,
그안에 _index.scss 파일를 각각 만들어 넣었습니다.

pages폴더 안에,
style.html파일을 만들고, 간단한 html을 작성하였습니다.
link rel="stylesheet" href="../css/style.css"     링크 연결해 주었구요.

scss > base 안에 _main.scss, _reset.scss 파일를 넣어 만들어 주었습니다.
scss > base > _index.scss 에 @forward "reset";   @forward "main";해 주었습니다.

여기서 부터 질문 드립니다.

첫번째,  
각각의 폴더 안에 있는 _index.scss는 어딘가로 모아 주어야 할 것 같은데,
어디에 연결 하는 지, 어떻게 연결 하는 지 
선생님 설명을 놓친듣 합니다. ㅜㅜ

두번째,  
프로젝트 폴더 > style.scss  에 @use "../pages/style";를 입력했더니 아래 사진과 같이 에러가 발생 하였습니다.
어느 부분에서 문제가 있는 것일까요?

지도 부탁드립니다.

![20240407_104403](https://github.com/rebehayan/SCSS-4th-Project/assets/165345287/f55aba69-85f0-45bc-8824-26ad45d46b58)

**Comment by rebehayan** [comment]
`첫번째 질문답변`
모아주는것이 아니라 UI구현했을때 필요한 구성파일을 @use로 로드 시켜야합니다. 한곳에 모아있지 않습니다.

`두번째 질문답변`
sytle.scss파일 기준으로 pages폴더에는 index.scss밖에 없습니다.. 로드를 잘못하셨습니다.
style.scss파일에는
```scss
@use 'page';
```
만 있으면됩니다.

그리고 현재 root폴더에 index.html이 없습니다.
꼭 생성해주셔야 합니다.

**Comment by my-zzu** [comment]
지금 막, 마지막에 말씀해주신 index.html 파일 생성했습니다.

다만, 질문 시점의 부라우저에는 수업시간의 방법대로 Go Live 화면 url창의 Go Live 주소뒤에 /pages/style.html/ 를 적어주어 연결 시킨 상태였습니다.

질문의 방법을 바꾸어서,
 
선생님 말씀대로,  scss폴더의 각 하위 폴더에 index.scss '만' 들었고,

브라우저 상에는  /pages/style.html/와 연결이 되어 있고,
style.html 컴파일된 css가 연결되어 있습니다.
컴파일된 css는 scss > style.scss 가 컴파일 되어 있습니다.

이상황에서의 질문입니다.
scss > base 안에는 reset.scss와 typography.scss   브라우저상에서 적용 될 수 있게 하려면, 어떤 파일에 어떤 명령을 입력해야하나요?
reset.scss 가 브라우저상에서 적용 되면 li요소에 list-style: none;이 적용 되어야 합니다.
첨부파일 사진은 list-style: none;가 적용 되지 않았으며, 고로 reset.scss가 적용 되지 않았음을 알수 있습니다.
typography.scss 또한 마찬가지 이겠죠.
우선적으로 이부분을 해결 하고자 합니다.

지도 부탁들립니다.
  

![20240407_2](https://github.com/rebehayan/SCSS-4th-Project/assets/165345287/5f49eb33-b901-4b2f-b338-df33c514c5e7)

**Comment by rebehayan** [comment]
scss > pages에 있는 표현하고자 하는 scss넣으시거나,
style.scss에 @use를 이용해 삽입하셔도 됩니다. reset은전역으로 적용되어야 하니깐요.

**Comment by my-zzu** [comment]
첫번째 방법으로 해결 하였습니다.

두번째 방법으로도 해결은 했는데,
@use "base";가 아니고,  @use "base"as *; 로 가능한것 같은데요.
왜 그래야하는지,  as * 의 의미가 무었인지가 궁금합니다.
@use "base"as *; 의 의미가 혹시 base 폴더 안에 있는 파일을 하나씨 따로 따로 삽입하라는 뜻인가요?
@use "base";의 의미와 다른 점이 궁금합니다.

어떨때 @use "base";를 쓰고, 어떨때 @use "base"as *;을 사용해야 하는지 구별이 가질 않아서요.ㅜㅜ

지도 부탁드립니다.

**Comment by my-zzu** [comment]
아. . 다시 해보니 @use "base";도 가능 하내요.

그래도 as * 의 의미는 궁금합니다.

**Comment by rebehayan** [comment]
우선 노션에 있는 @use,@forward라는 글을 읽어보시는걸 추천드립니다.


as는 CSS로 컴파일 되지 않는 코드에 한해서 사용하는 것으로 이해하시면 됩니다.
예를들어 
mixin에 있는 background를 사용하고 싶으면

`@use '../mixin/background'; `
라고 호출하게 되고
코드를 사용할때에는

```scss
div {
  @include background.background( 믹스인관련 인수값);
}
```
이렇게 사용해야 합니다.
처음사용된background 는 파일명을 지칭하고
두번째 사용된 background는 그 파일에 있는 background 믹스인명입니다.

이렇게 계속 쓰기 매번 불편하죠 
그래서 

`@use '../mixin/background' as bg; `

라고 쓸수있습니다.

```scss
div {
  @include bg.background( 믹스인관련 인수값);
}
```
이런식으로 표현하는데 이것또한.. 불편한감이 있죠
그래서 이런 내용을 쉽게 풀기 위해서


`@use '../mixin/background' as *; `

이렇게 사용됩니다.
*는 CSS에서 모든 선택자죠..
즉 background파일에 있는 모든 정의된것을 가지고오겠다는 뜻입니다.


다시 돌아와서 그렇다면 왜 base는 그걸 쓰지 않는가?

base는 CSS로 컴파일 되어야 하는 것들로 구성되어 있어서 그렇습니다.
mixin, function, variable같은 SCSS만의 정의된 파일은 참조를 필요로 하는데
base는 그렇지 않습니다.

그래서 as를 쓰지 않아도 표현되게 됩니다.
